# Generated by Django 4.0.4 on 2022-09-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='download_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('downloads', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('temporary_role', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(max_length=200)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('annual_package', models.IntegerField(null=True)),
                ('address', models.TextField()),
                ('appointmentletter_issued_on', models.DateTimeField(blank=True, null=True)),
                ('termination_letter_issued', models.DateTimeField(blank=True, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=10, null=True)),
                ('service_agreement_issued_date', models.DateTimeField(blank=True, null=True)),
                ('letter_of_intent_issued_date', models.DateTimeField(blank=True, null=True)),
                ('penaulty', models.IntegerField(blank=True, null=True)),
                ('traning_period', models.IntegerField(blank=True, null=True)),
                ('offer_letter_issued_datetime', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('role', models.CharField(max_length=400)),
                ('joinied_date', models.DateField()),
                ('leaving_date', models.DateField()),
                ('internship_letter_issue_date', models.DateTimeField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('record', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='test_store_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Termination_Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Service_letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Offer_Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Intent_Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Intenship_certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.interns')),
            ],
        ),
        migrations.CreateModel(
            name='Hike_letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('Created', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Employees_hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike', models.IntegerField()),
                ('hike_letter_issued_date', models.DateTimeField(blank=True, null=True)),
                ('hike_duration_start_year', models.DateField(blank=True, null=True)),
                ('hike_duration_end_year', models.DateField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
    ]
